services:
  geocoder:
    image: traccar/traccar-geocoder
    environment:
      - PBF_URLS=https://download.geofabrik.de/europe/monaco-latest.osm.pbf
    ports:
      - "3000:3000"
    volumes:
      - geocoder-data:/data

  search:
    image: traccar/traccar-geocoder
    command: search
    environment:
      - DATA_DIR=/data
      - SEARCH_BIND_ADDR=0.0.0.0:3001
    ports:
      - "3001:3001"
    volumes:
      - geocoder-data:/data
    depends_on:
      - geocoder

volumes:
  geocoder-data:
